//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BLL.ServiceDados {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDados.ServiceDBSoap")]
    public interface ServiceDBSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDados", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable GetDados();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDados", ReplyAction="*")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDadosAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceDBSoapChannel : BLL.ServiceDados.ServiceDBSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceDBSoapClient : System.ServiceModel.ClientBase<BLL.ServiceDados.ServiceDBSoap>, BLL.ServiceDados.ServiceDBSoap {
        
        public ServiceDBSoapClient() {
        }
        
        public ServiceDBSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceDBSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDBSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceDBSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetDados() {
            return base.Channel.GetDados();
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDadosAsync() {
            return base.Channel.GetDadosAsync();
        }
    }
}
